### ISSUE TITLE
Enabling_22 - hj_01_03_05_05 - Activity not registering as complete

### ISSUE THREAD

**Issue by sdub** [danb-dliflc/DliActivities#357]
Activity not registering as complete after all blanks correctly filled in. Tried twice with no success

**Comment by proti9** [comment]
Items should have same words with the pointed words on the sentence. For example, on set 1, the item 2 pointing position 2 (जाओ) is different to the second word on the sentent (जाओ।). Then, the presentation side shows tree blank spaces instead of four blank spaces. And, you can not complete the set. Please check contents on the xml generator.

**Comment by sdub** [comment]
Great catch!!!!! Thank you, will check and update the Generator.
